import {
  collection,
  doc,
  getDocs,
  setDoc,
  limit,
  query
} from 'firebase/firestore';
import { db } from '../firebase/config';
import type { PropertyDocument } from '../types/firebaseModels';

export const REALISTIC_INDIAN_PROPERTIES: PropertyDocument[] = [
  {
    propertyId: 'lokha-chn-01',
    ownerId: 'owner-raj-chennai',
    ownerName: 'K. Rajasekaran',
    ownerPhone: '+91 98401 23456',
    ownerEmail: 'rajasekaran.estates@gmail.com',
    listedByName: 'K. Rajasekaran (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: '04-128-092-8812',
    ebProvider: 'TANGEDCO (Tamil Nadu Electricity Board)',
    ebTariff: 'Tariff IA Domestic High Tension',
    govDocType: 'Patta & Chitta Transfer Deed',
    govDocNumber: 'TN-CH-PATTA-2022-882194',
    isGovEbVerified: true,
    agentId: 'agent-rajesh-sharma',
    title: 'The Sovereign Sea Villa on ECR Promenade',
    description: 'Bespoke colonial beachfront mansion set on a 1.2-acre private coconut grove along the Bay of Bengal. Features double-height Italian marble foyer, private infinity lap pool, independent staff quarters, and uninterrupted sea sunrise views.',
    propertyType: 'Villa',
    listingType: 'Sale',
    price: 340000000,
    rentAmount: 450000,
    monthlyRent: 450000,
    leaseAmount: 55000000,
    securityDeposit: 1500000,
    bedrooms: 5,
    bathrooms: 6,
    balconies: 4,
    area: 6800,
    builtUpArea: 6800,
    carpetArea: 5900,
    plotArea: 12000,
    areaUnit: 'sq.ft',
    floor: 'G+2 Floors',
    totalFloors: 3,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    constructionYear: 2023,
    address: 'Seaside Boulevard, Off East Coast Road, Uthandi',
    locality: 'ECR Golden Beach Corridor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    pincode: '600119',
    latitude: 12.8715,
    longitude: 80.2520,
    amenities: [
      'Private Direct Beach Access',
      'Temperature-Controlled Pool',
      'Italian Statuario Marble',
      'Solar Power with 24/7 Battery Storage',
      '4 Covered Luxury Car Parks',
      'Landscaped Zen Water Garden'
    ],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'TN/01/Building/0192/2022',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-01-15T09:30:00.000Z',
    updatedAt: '2024-01-15T09:30:00.000Z',
    views: 1420,
    viewsCount: 1420,
    favoritesCount: 88,
    enquiryCount: 24,
    isFeatured: true
  },
  {
    propertyId: 'lokha-blr-02',
    ownerId: 'owner-anand-bengaluru',
    ownerName: 'Anand Mahindra Rao',
    ownerPhone: '+91 98840 99887',
    ownerEmail: 'anand.rao.blr@gmail.com',
    listedByName: 'Anand Rao (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: 'BESCOM-KA-0912-771',
    ebProvider: 'BESCOM (Bangalore Electricity Supply Co)',
    ebTariff: 'LT-2(a) Domestic Pure Line',
    govDocType: 'BDA Khata Certificate (A-Khata)',
    govDocNumber: 'BBMP/A-KHATA/2023/449102',
    isGovEbVerified: true,
    agentId: 'agent-priya-menon',
    title: 'Sky Duplex Penthouse over Indiranagar Canopy',
    description: 'Spectacular 4 BHK penthouse spanning the 22nd and 23rd floors with 360-degree panoramic views of Bengaluru green tree canopy and sunset skyline. Features 24ft double-height ceiling in the living lounge, private plunge pool, and smart home automation.',
    propertyType: 'Penthouse',
    listingType: 'Rent',
    price: 185000000,
    rentAmount: 285000,
    monthlyRent: 285000,
    leaseAmount: 32000000,
    securityDeposit: 1200000,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    area: 5200,
    builtUpArea: 5200,
    carpetArea: 4450,
    areaUnit: 'sq.ft',
    floor: '22nd of 24',
    totalFloors: 24,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    constructionYear: 2023,
    address: '100 Feet Road, HAL 2nd Stage, Indiranagar',
    locality: 'Indiranagar 100ft Promenade',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    pincode: '560038',
    latitude: 12.9784,
    longitude: 77.6408,
    amenities: [
      'Private Terrace Plunge Pool',
      'Private Elevator Keycard Access',
      'Smart Home Lighting & Climate Automation',
      'Italian Scavolini Kitchen with Sub-Zero Appliances',
      '3 Dedicated Basement EV Charging Slots',
      'Clubhouse & Concierge Lounge'
    ],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'PRM/KA/RERA/1251/310/PR/180222/001402',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-02-01T11:00:00.000Z',
    updatedAt: '2024-02-01T11:00:00.000Z',
    views: 1890,
    viewsCount: 1890,
    favoritesCount: 114,
    enquiryCount: 42,
    isFeatured: true
  },
  {
    propertyId: 'lokha-mum-03',
    ownerId: 'owner-farhan-mumbai',
    ownerName: 'Farhan Merchant',
    ownerPhone: '+91 98200 44556',
    ownerEmail: 'farhan.merchant@pali-estates.com',
    listedByName: 'Farhan Merchant (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: 'ADANI-MH-MUM-891002',
    ebProvider: 'Adani Electricity Mumbai Ltd',
    ebTariff: 'Domestic LT-I B',
    govDocType: 'BMC Registered Conveyance & Share Certificate',
    govDocNumber: 'MH-MUM-REG-2021-99812',
    isGovEbVerified: true,
    agentId: 'agent-rohit-mehta',
    title: 'The Sea Vista Horizon on Pali Hill Promenade',
    description: 'Iconic sea-facing residence perched on the quiet leafy crest of Pali Hill. Breathtaking unobstructed vistas of the Arabian Sea, floor-to-ceiling soundproof German glass, private gym, and valet parking.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 245000000,
    rentAmount: 390000,
    monthlyRent: 390000,
    leaseAmount: 48000000,
    securityDeposit: 1500000,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 2,
    area: 4100,
    builtUpArea: 4100,
    carpetArea: 3500,
    areaUnit: 'sq.ft',
    floor: '16th of 20',
    totalFloors: 20,
    facing: 'West',
    constructionStatus: 'Ready to Move',
    constructionYear: 2022,
    address: 'Pali Hill, Near Nargis Dutt Road, Bandra West',
    locality: 'Pali Hill, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pincode: '400050',
    latitude: 19.0645,
    longitude: 72.8280,
    amenities: [
      'Unobstructed Sunset Arabian Sea Views',
      'Double Soundproof Schuco Facade',
      'Private Temperature-Controlled Cellar',
      'Resident Lounge with Private Chef Station',
      '3 Stacking Hydraulic Parking Slots',
      '24/7 Uniformed Valet & Armed Perimeter'
    ],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'P51800019482',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-01-20T14:20:00.000Z',
    updatedAt: '2024-01-20T14:20:00.000Z',
    views: 2310,
    viewsCount: 2310,
    favoritesCount: 160,
    enquiryCount: 58,
    isFeatured: true
  },
  {
    propertyId: 'lokha-del-04',
    ownerId: 'owner-siddharth-delhi',
    ownerName: 'Siddharth Chadha',
    ownerPhone: '+91 99100 23881',
    ownerEmail: 'siddharth.chadha@delhirealty.in',
    listedByName: 'Siddharth Chadha (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: 'BSES-DL-NDMC-091823',
    ebProvider: 'NDMC (New Delhi Municipal Council)',
    ebTariff: 'Domestic Category I',
    govDocType: 'L&DO Registered Freehold Conveyance Deed',
    govDocNumber: 'DL-LDO-JORBAGH-2020-00129',
    isGovEbVerified: true,
    agentId: 'agent-vikram-singh',
    title: 'The Diplomatic Manor overlooking Jor Bagh Park',
    description: 'Rare colonial architectural triumph directly facing the manicured greenery of Jor Bagh. Soaring 14ft ceilings, Burma teakwood flooring, landscaped courtyard with fountain, and full biometric security fencing.',
    propertyType: 'Villa',
    listingType: 'Sale',
    price: 490000000,
    rentAmount: 650000,
    monthlyRent: 650000,
    leaseAmount: 85000000,
    securityDeposit: 2500000,
    bedrooms: 6,
    bathrooms: 7,
    balconies: 5,
    area: 8500,
    builtUpArea: 8500,
    carpetArea: 7200,
    plotArea: 14400,
    areaUnit: 'sq.ft',
    floor: 'G+2 Floors',
    totalFloors: 3,
    facing: 'North',
    constructionStatus: 'Ready to Move',
    constructionYear: 2021,
    address: 'Block 4, Jor Bagh, Near Safdarjung Tomb',
    locality: 'Jor Bagh Diplomatic Corridor',
    city: 'Delhi',
    state: 'Delhi NCR',
    country: 'India',
    pincode: '110003',
    latitude: 28.5872,
    longitude: 77.2185,
    amenities: [
      'Direct Green Park Frontage',
      'Burma Teak Woodwork & Brass Accents',
      'Private Swimming Pool in Inner Courtyard',
      'Sub-Zero Temperature Controlled Food Cellar',
      'Guardroom & Independent Driver Suites',
      '100% Generator Backup & Solar Water Plant'
    ],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'DLRERA2020P0018',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-01-10T08:00:00.000Z',
    updatedAt: '2024-01-10T08:00:00.000Z',
    views: 1980,
    viewsCount: 1980,
    favoritesCount: 92,
    enquiryCount: 31,
    isFeatured: true
  },
  {
    propertyId: 'lokha-hyd-05',
    ownerId: 'owner-venkat-hyderabad',
    ownerName: 'Venkat Reddy',
    ownerPhone: '+91 98490 11223',
    ownerEmail: 'venkat.reddy.jubilee@gmail.com',
    listedByName: 'Venkat Reddy (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: 'TSSPDCL-HYD-JUB-9910',
    ebProvider: 'TSSPDCL (Telangana Southern Power)',
    ebTariff: 'Category I Domestic',
    govDocType: 'GHMC Approved Building Permission & Mutation',
    govDocNumber: 'GHMC/WZ/2023/881273',
    isGovEbVerified: true,
    agentId: 'agent-rajesh-sharma',
    title: 'The Palm Serenade Estate on Jubilee Hills Road 36',
    description: 'Modernist architectural marvel built on a boulder-terraced ridge in Jubilee Hills. Features cantilevered infinity pool, private home theatre with Dolby Atmos acoustic treatment, water cascade wall, and lush tropical lawns.',
    propertyType: 'Villa',
    listingType: 'Lease',
    price: 280000000,
    rentAmount: 350000,
    monthlyRent: 350000,
    leaseAmount: 42000000,
    securityDeposit: 1400000,
    bedrooms: 5,
    bathrooms: 6,
    balconies: 3,
    area: 7200,
    builtUpArea: 7200,
    carpetArea: 6100,
    plotArea: 10800,
    areaUnit: 'sq.ft',
    floor: 'G+2 Floors',
    totalFloors: 3,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    constructionYear: 2023,
    address: 'Road No. 36, Jubilee Hills, Near Peddamma Temple',
    locality: 'Jubilee Hills Ridge',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    pincode: '500033',
    latitude: 17.4319,
    longitude: 78.4073,
    amenities: [
      'Cantilevered Ridge Infinity Pool',
      'Private 12-Seat 4K Dolby Atmos Cinema',
      'Natural Boulder Garden Landscaping',
      'Italian Boffi Kitchen with Wine Cooler',
      '5 Car Parking with Electric Turntable',
      'Integrated Solar Hybrid Microgrid'
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'P02400003189',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-02-10T10:15:00.000Z',
    updatedAt: '2024-02-10T10:15:00.000Z',
    views: 1650,
    viewsCount: 1650,
    favoritesCount: 78,
    enquiryCount: 29,
    isFeatured: true
  },
  {
    propertyId: 'lokha-goa-06',
    ownerId: 'owner-claudia-goa',
    ownerName: 'Claudia Fernandes',
    ownerPhone: '+91 98221 66778',
    ownerEmail: 'claudia.goa.estates@gmail.com',
    listedByName: 'Claudia Fernandes (Owner)',
    ownershipType: 'Self',
    ebConsumerNumber: 'GOA-ELEC-CND-44910',
    ebProvider: 'Goa Electricity Department',
    ebTariff: 'Domestic LT-D',
    govDocType: 'Panchayat Approved Title & Sanad Conversion',
    govDocNumber: 'GA-BAR-SANAD-2021-00912',
    isGovEbVerified: true,
    agentId: 'agent-rajesh-sharma',
    title: 'The Portuguese Heritage Estate with River Frontage',
    description: 'Restored 19th-century Portuguese manor set alongside the serene waters of the Nerul River. High wood-trussed terracotta ceilings, wrap-around balcão veranda, private jetty, and freshwater pool surrounded by frangipani trees.',
    propertyType: 'Villa',
    listingType: 'Stay',
    price: 145000000,
    rentAmount: 32000,
    monthlyRent: 220000,
    stayNightlyRate: 32000,
    stayMaxGuests: 8,
    leaseAmount: 22000000,
    securityDeposit: 600000,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    area: 4500,
    builtUpArea: 4500,
    carpetArea: 3800,
    plotArea: 22000,
    areaUnit: 'sq.ft',
    floor: 'G+1 Floor',
    totalFloors: 2,
    facing: 'West',
    constructionStatus: 'Ready to Move',
    constructionYear: 2021,
    address: 'Nerul River Road, Near Coco Beach, Candolim',
    locality: 'Nerul River Promenade',
    city: 'Goa',
    state: 'Goa',
    country: 'India',
    pincode: '403515',
    latitude: 15.5180,
    longitude: 73.7845,
    amenities: [
      'Private River Jetty for Speedboat',
      'Authentic Azulejos Ceramic Tiles',
      'Freshwater Garden Swimming Pool',
      'Outdoor Dining Gazebo with Barbecue Pit',
      'High-Speed Satellite Internet & Solar Inverter',
      'Full-Time In-House Cook & Butler Service'
    ],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlan: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    status: 'available',
    propertyStatus: 'active',
    verificationStatus: 'verified',
    reraNumber: 'PRGO04190772',
    reraRegistered: true,
    furnishedStatus: 'Fully Furnished',
    createdAt: '2024-02-15T12:30:00.000Z',
    updatedAt: '2024-02-15T12:30:00.000Z',
    views: 1740,
    viewsCount: 1740,
    favoritesCount: 130,
    enquiryCount: 38,
    isFeatured: true
  }
];

export async function seedPropertiesIfEmpty(): Promise<void> {
  try {
    const q = query(collection(db, 'properties'), limit(1));
    const snap = await getDocs(q);
    if (snap.empty) {
      console.log('[SeedService] Seeding initial verified Indian properties to Cloud Firestore...');
      for (const p of REALISTIC_INDIAN_PROPERTIES) {
        await setDoc(doc(db, 'properties', p.propertyId), p);
      }
      console.log('[SeedService] Successfully provisioned', REALISTIC_INDIAN_PROPERTIES.length, 'properties.');
    }
  } catch (err) {
    console.warn('[SeedService] Cloud Firestore seed note:', err);
  }
}
